package day6;

//This class is created to help method testPostusingPOJO() of class DiffWaysToCreatePostRequestBody
public class POJO_PostRequest_StudentAPI  {
	
	String name;
	String location;
	String phone;
	String courses[];
	//Here the below methods can be automatically generated by drag and highlight all above 4 variables then go to Source option and select Generate Getters and Setters... 
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getLocation() {
		return location;
	}
	public void setLocation(String location) {
		this.location = location;
	}
	public String getPhone() {
		return phone;
	}
	public void setPhone(String phone) {
		this.phone = phone;
	}
	public String[] getCourses() {
		return courses;
	}
	public void setCourses(String[] courses) {
		this.courses = courses;
	}
	

}
